---
title: "Meu primeiro relatório"
author: "Luiz Otavio"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cálculos matemáticos

## Para criar um bloco de códigos, selecione e clique no c (verde), com marca de + na barra superior

Estes são os meus primeiros códigos em linguagem R.

```{r}

conjunto_vogais <- c("a", "e", "i", "o", "u")
conjunto_vogais

conjunto_numeros <- c(1, 2, 3, 4, 5)
conjunto_numeros

lista_frutas <- c("abacate", "maça", "pera", "abacaxi")
lista_frutas

soma <- 1+1
soma


multiplica <- 32*31
multiplica

vogais <- c("a", "e", "i", "o", "u")
vogais

lista_frutas <- c("maçã", "abacate", "banana", "uva")
lista_frutas

numeros_decimais <- c(3.1, 2.4, 10.8, 6.7)
numeros_decimais



```

Aqui irei crir algumas matrizes.

```{r}

A <- matrix (c(1, 2, 3, 1), nrow = 2, ncol = 2, byrow = TRUE)
A

B <- matrix (c(0, 1, 4, 0), nrow = 2, ncol = 2, byrow = TRUE)
B


#soma de A+ B

soma_A_B <- A + B
soma_A_B

# Subtração  A - B

diferenca_A_B <- A - B
diferenca_A_B

# Multiplicação de A * B

multiplica_A_B <- A %*% B
multiplica_A_B

```

```{r}
 # Calcular uma matriz inversa


z <- matrix(c(-2, 4, 5, -9), nrow = 2, ncol = 2, byrow = TRUE)
z

z_inversa <- solve(z)
z_inversa

y <- matrix(c(1, 0, 0, 1, 3, 1, 1, 2, 0), nrow = 3, ncol = 3, byrow = TRUE)
y

y_inversa <- solve(y)
y_inversa




# cálculo de determinante de matrizes

r <- matrix(c(4, -5, 2, -3), nrow = 2, ncol = 2, byrow = TRUE)
r

determinante_r <- det(r)
determinante_r

q <- matrix(c(-1, 2, 0, 3, -2, 1, 4, 0, 2), nrow = 3, ncol = 3, byrow = TRUE)
q

determinante_q <- det(q)
determinante_q



```
