Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2026
Var
   numero: inteiro // Seção de Declarações das variáveis

Inicio
escreva("Digite um numero inteiro:")// Seção de Comandos, procedimento, funções, operadores, etc...
leia(numero)
se(numero > 5) entao
  escreva("O número é maior que cinco.")

fimse

Fimalgoritmo